// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzpayeckolpfflgvkqvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cGF5ZWNrb2xwZmZsZ3ZrcXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTE2OTEsImV4cCI6MjA2NTI4NzY5MX0.56YUDNYwuTMYpc2wWdftlXr0nakH8Ru4JTUXj7HOv5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);